### ISSUE TITLE
Conversation

### ISSUE THREAD

**Issue by jonrysimbolon** [lana-jo/Android-POS#1]
mas, ini json yg bermasalah, difile apa ya ?

**Comment by lana-jo** [comment]
file ouput.json

**Comment by lana-jo** [comment]
> mas, ini json yg bermasalah, difile apa ya ?
file ouput.json

**Comment by jonrysimbolon** [comment]
di folder assets gk ada file output.json

**Comment by jonrysimbolon** [comment]
dan juga, ini saya jalani belum bisa karna project/folder `AssetMedia` dan `DialogSheet` nya gk ada

**Comment by lana-jo** [comment]
> di folder assets gk ada file output.json

maksutnya outlet
untuk assetMedia dan Dialogsheet itu library tidak untuk umum mas, maaf

**Comment by jonrysimbolon** [comment]
mmm, bgitu ya, brrti cuma bisa kasih saran doang lah ini ya ?
gk bisa saya jalani di device gitu ya ?

**Comment by lana-jo** [comment]
> mmm, bgitu ya, brrti cuma bisa kasih saran doang lah ini ya ? gk bisa saya jalani di device gitu ya ?

mungkin kalau masnya matiin librarynya dan penggunaannya, bisa dijalankan mas. itu buat menampilkan dialog sama media aja kok, di json belum ada kedua itu

**Comment by jonrysimbolon** [comment]
ok wait

**Comment by jonrysimbolon** [comment]
bntr ya mas, saya tak coba hapusi satu satu, karna lumayan juga

**Comment by jonrysimbolon** [comment]
ok mas, ini sudah jalan, coba jelaskan lebih terperinci, masalahnya dimna dan mau nya itu gmna

**Comment by jonrysimbolon** [comment]
oke mas, saya udah dapat poinnya, berarti mas ini ingin mengubah file yang ada di file json nya asset (folder) ya ?
kalo iya, itu gk bisa mas, mas harus bikin file json baru di local storage atau menyimpan data menggunakan sqlite/room, menyimpan data dengan format json mungkin bukan cara yang lazim dibuat tapi possible untuk dilakukan, perubahannya banyak atau tidak kalo di lakukan secara sqlite/room ? banyak, karna itu saya sarankan pelajari cara membaca dan mengedit kemudian menyimpan file untuk local storage

**Comment by lana-jo** [comment]
> oke mas, saya udah dapat poinnya, berarti mas ini ingin mengubah file yang ada di file json nya asset (folder) ya ? kalo iya, itu gk bisa mas, mas harus bikin file json baru di local storage atau menyimpan data menggunakan sqlite/room, menyimpan data dengan format json mungkin bukan cara yang lazim dibuat tapi possible untuk dilakukan, perubahannya banyak atau tidak kalo di lakukan secara sqlite/room ? banyak, karna itu saya sarankan pelajari cara membaca dan mengedit kemudian menyimpan file untuk local storage

maaf mas, baru balas. kalau hanya menggunakan viewmodel dan model aja masnya tahu caranya?

**Comment by jonrysimbolon** [comment]
gini mas, model dan view model itu hanya perantara.
yg saya tangkap disini adalah, jika mas ingin data yg dinamis (bisa diubah-ubah) hanya ada 2 cara, by local atau remote.

remote sudah fix restapi, local ada beberapa, yaitu variable, preference, room/sqlite, localstorage, nah kalo mas udh mulai denga file json dalam asset, mas haru 'paksa' belajar local storage, karna flownya sama dan bisa diubah ubah isinya (dinamis), berbeda dengan file json dari folder asset (statis).

**Comment by lana-jo** [comment]
> gini mas, model dan view model itu hanya perantara. yg saya tangkap disini adalah, jika mas ingin data yg dinamis (bisa diubah-ubah) hanya ada 2 cara, by local atau remote.
> 
> remote sudah fix restapi, local ada beberapa, yaitu variable, preference, room/sqlite, localstorage, nah kalo mas udh mulai denga file json dalam asset, mas haru 'paksa' belajar local storage, karna flownya sama dan bisa diubah ubah isinya (dinamis), berbeda dengan file json dari folder asset (statis).

kalau pakai variable gimana mas? kalau localstorage waktunya ndak cukup soalnya kamis dah harus direview langsung sama orang be biar di isi datanya, ui masih seadanya juga soale ui masih belum ngasih desain

**Comment by jonrysimbolon** [comment]
saya tidak merekomendasi variable mas, karna dia bisa berubah secara tidak terkendali dan rentan error (karna memang dia tidak didesign untuk penyimpanan secara global).

bisa aja mas edit menjadi "A", terus dia berubah menjadi "B", atau bahkan bisa error, karna itu hal yg tricky dan tidak disarankan.

**Comment by lana-jo** [comment]
> saya tidak merekomendasi variable mas, karna dia bisa berubah secara tidak terkendali dan rentan error (karna memang dia tidak didesign untuk penyimpanan secara global).
> 
> bisa aja mas edit menjadi "A", terus dia berubah menjadi "B", atau bahkan bisa error, karna itu hal yg tricky dan tidak disarankan.

buat crud 1 menu aja kok mas

**Comment by jonrysimbolon** [comment]
yups, karna itu saya tidak sarankan variable mas, sangat sangat tidak didesign untuk crud

**Comment by lana-jo** [comment]
> yups, karna itu saya tidak sarankan variable mas, sangat sangat tidak didesign untuk crud

aku tadi disarain pakai variable dulu sama benya mas, variablenya disambungin ke model sama viewmodel

**Comment by lana-jo** [comment]
> yups, karna itu saya tidak sarankan variable mas, sangat sangat tidak didesign untuk crud

tapi bingung cara pakai variblenya wkwk

**Comment by jonrysimbolon** [comment]
jujur, saya gagal paham sama yg di sarani sama BE nya, karna ketika activity/fragmentnya sudah pake intent atau pergi ke screen lain, itu variablenya jadi kosong

**Comment by jonrysimbolon** [comment]
oh i see, variable nya diisiin sama data yg dinamis (default kosong) dan di share ke activity lain menggunakan viewmodel yg sama.

yakin mas mau pake itu, rombaknya banyak tuh + memang harus clean code atau semi clean code.

**Comment by lana-jo** [comment]
> oh i see, variable nya diisiin sama data yg dinamis (default kosong) dan di share ke activity lain menggunakan viewmodel yg sama.
> 
> yakin mas mau pake itu, rombaknya banyak tuh + memang harus clean code atau semi clean code.

gpp mas, kata be nya nanti buat data dummy dulu di viewmodel terus di konekin ke model, aku dari tadi belum nemu caranya

**Comment by jonrysimbolon** [comment]
data dummy itu artinya data statik bukan ?
kalo bukan, brrti perlu nerapin ini di vm
1. buat variable var di viewmodel
2. convert var tersebut kedalam data yg bisa dibaca form
3. edit dan update data melalui vm yg sama di berbagai activity yg digunakan.

**Comment by lana-jo** [comment]
> data dummy itu artinya data statik bukan ? kalo bukan, brrti perlu nerapin ini di vm
> 
> 1. buat variable var di viewmodel
> 2. convert var tersebut kedalam data yg bisa dibaca form
> 3. edit dan update data melalui vm yg sama di berbagai activity yg digunakan.

tipe data variablenya apa ya mas kalau boleh tahu? varnya itu isinya mutablelistkah? point 2,3 munkin masukkan ke function gitu ya?

**Comment by jonrysimbolon** [comment]
data dummy kn ?
kalo iya
1. String => isinya semua yg ada dalam oulet.json, tapi string
2. convert variable itu ke data yg bisa di baca oleh form dengan function
3. update data yg ada di vm berdasarkan edit yg dilakukan form edit atau form new

**Comment by lana-jo** [comment]
> data dummy kn ? kalo iya
> 
> 1. String => isinya semua yg ada dalam oulet.json, tapi string
> 2. convert variable itu ke data yg bisa di baca oleh form dengan function
> 3. update data yg ada di vm berdasarkan edit yg dilakukan form edit atau form new

kaya gini bisa mas??

var dummy = mutableListOf(
		" \"id\": 1,\n"+"    \"name\": \"outlet 1\",\n"+"    \"address\": \"Jl. Menoreh Raya No.76a, Bendan Duwur, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50235\",\n"+"    \"outlet_user\": 21",
		"  \"id\": 2,\n"+"    \"name\": \"outlet 2\",\n"+"    \"address\": \"Jl. Tlogosari Raya II No.21, Tlogosari Kulon, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50196\",\n"+"    \"outlet_user\": 22",
		" \"id\": 3,\n"+"    \"name\": \"outlet 3\",\n"+"    \"address\": \"Jl. KaranganyarNo.578, Brumbumgan, Gabahan, Semarang Tengah, Semarang City, Central Java 50135\",\n"+"    \"outlet_user\": 23",
		"  \"id\": 4,\n"+"    \"name\": \"outlet 4\",\n"+"    \"address\": \"Jl. Jati Raya, Srondol Wetan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50263\",\n"+"    \"outlet_user\": 24"
	)

**Comment by jonrysimbolon** [comment]
ya cba saja, kalo tidak error, lanjut.

**Comment by lana-jo** [comment]
> ya cba saja, kalo tidak error, lanjut.

untuk menampilkan ke viewnya gimana mas? masih pake gson.fromjson atau gimana?
